config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations',
    # passwords: 'users/passwords',
    # registrations: 'users/registrations',
    # unlocks: 'users/unlocks'
  }
  match '/users/finish_signup' => 'users#finish_signup', via: %i[get patch], as: :finish_signup

  root 'purchases#index'

  get 'purchases/index'
  get 'purchases/history'

  get 'inventory/index'

  get 'permissions/index'

  resources :categories

  namespace :api, defaults: { format: :json } do
    resources :orders,      only: %i[index create show]
    resources :items,       only: %i[index create show update]
    resources :users,       only: %i[index show update] do
      resources :user_abilities,    only: [:create]
      resources :orders,            only: [:index]
    end
    resources :user_abilities, only: [:destroy]
  end

  get 'robots', to: 'robot#show'
  get 'robot', to: 'robot#show'
end

app/controllers/inventory_controller.rb
# frozen_string_literal: true

class InventoryController < ApplicationController
  before_action :authenticate_user!

  def index
    return user_not_authorized unless current_user.can_view_inventory?

    @categories = Category.order(:name)
    @new_item = Item.new
  end
end

app/views/inventory/index.html.erb
<div class="container-fluid">
  <% if current_user.can_add_inventory? %>
    <div class="row">
      <div class="panel col-sm-offset-1 col-sm-10">
        <div class="panel-heading text-center">
          <h4>Add new items to sell</h4>
        </div>
        <div class="panel-body">
          <%= form_for @new_item, url: api_items_path, html: {id: "new-item", role: "form"}, remote: true do |f| %>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :type_id, value: "Type id" %>
              <%= f.number_field :type_id, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :category_id %>
              <%= f.select :category_id, options_for_select(Category.names_for_select), {include_blank: "Select a category"}, { class: "form-control" } %>
            </div>
            <div class="form-group">
              <%= f.label :for_sale %>
              <%= f.check_box :for_sale, class: "form-control", "data-on-text"=>"Y", "data-off-text"=>"N" %>
            </div>
            <div class="form-group">
              <%= f.label :rendered %>
              <%= f.check_box :rendered, class: "form-control", "data-on-text"=>"Y", "data-off-text"=>"N" %>
            </div>
            <div class="form-group">
              <%= f.submit "Add Item", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="panel col-sm-offset-1 col-sm-10">
      <% @categories.each do |category| %>
        <div class="panel-heading text-center">
          <h4><%= category.name.pluralize %></h4>
        </div>
        <div class="panel-body items-container">
          <div class="row">
            <% category.items.order(:name).each do |item| %>
              <%= render "items/item", item: item %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>