config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations',
    # passwords: 'users/passwords',
    # registrations: 'users/registrations',
    # unlocks: 'users/unlocks'
  }
  match '/users/finish_signup' => 'users#finish_signup', via: %i[get patch], as: :finish_signup

  root 'purchases#index'

  get 'purchases/index'
  get 'purchases/history'

  get 'inventory/index'

  get 'permissions/index'

  resources :categories

  namespace :api, defaults: { format: :json } do
    resources :orders,      only: %i[index create show]
    resources :items,       only: %i[index create show update]
    resources :users,       only: %i[index show update] do
      resources :user_abilities,    only: [:create]
      resources :orders,            only: [:index]
    end
    resources :user_abilities, only: [:destroy]
  end

  get 'robots', to: 'robot#show'
  get 'robot', to: 'robot#show'
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  # Associations
  has_many :items

  # Validations
  validates :name,      presence: true
  validates :name,      uniqueness: true
  before_destroy :check_for_items

  def self.names
    Category.order(:name).pluck(:name)
  end

  def self.names_for_select
    Category.order(:name).pluck(:name, :id)
  end

private

  def check_for_items
    if items.empty?
      return
    end
    errors.add :base, 'cannot be destroyed while category has items in it'
    throw :abort
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories
  # GET /categories.json
  def index
    return user_not_authorized unless current_user.can_view_category?

    @categories = Category.order :name
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    return user_not_authorized unless current_user.can_view_category?
  end

  # GET /categories/new
  def new
    return user_not_authorized unless current_user.can_add_category?

    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    return user_not_authorized unless current_user.can_change_category?
  end

  # POST /categories
  # POST /categories.json
  def create
    return user_not_authorized unless current_user.can_add_category?

    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    return user_not_authorized unless current_user.can_change_category?

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    return user_not_authorized unless current_user.can_change_category?

    respond_to do |format|
      if @category.destroy
        format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="page-header">
  <h1>Editing Category</h1>
</div>

<div class='panel'>
  <div class='panel-body'>
    <%= render 'form' %>
  </div>
</div>

<div class='panel'>
  <div class='panel-body'>
    <%= link_to 'Show', @category %> |
    <%= link_to 'Back', categories_path %>
  </div>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Categories</h1>
</div>

<div class='panel'>
  <div class='panel-body'>
    <div class="table-responsive">
      <table class="table table-hover table-condensed">
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="2">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= link_to category.name, category %></td>
              <td>
                <% if current_user.can_change_category? %>
                  <%= link_to 'Edit', edit_category_path(category) %>
                <% end %>
              </td>
              <td class='danger'>
                <% if current_user.can_change_category? %>
                  <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class='panel'>
  <div class='panel-body'>
    <% if current_user.can_add_category? %>
      <%= link_to 'New Category', new_category_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="page-header">
  <h1>New Category</h1>
</div>

<div class='panel'>
  <div class='panel-body'>
    <%= render 'form' %>
  </div>
</div>

<div class='panel'>
  <div class='panel-body'>
    <%= link_to 'Back', categories_path %>
  </div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><%= @category.name.pluralize %></h1>
</div>

<div class='panel'>
  <div class='panel-body'>
    <% if @category.items.empty? %>
      There are no items in this category
    <% else %>
      <% @category.items.order(:name).each do |item| %>
        <div data-item-id="<%= item.id %>" class="item-container
            col-xs-6
            col-sm-4
            col-md-3
            col-lg-2">
          <h4><%= item.name %></h4>
          <a class="item-thumb">
            <%= image_tag item.image_url, class: "img-responsive img-thumbnail", alt: "Image of #{item.name}" %>
          </a>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class='panel'>
  <div class='panel-body'>
    <%= link_to 'Edit', edit_category_path(@category) %> |
    <%= link_to 'Back', categories_path %>
  </div>
</div>