config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations: 'users/confirmations',
    # passwords: 'users/passwords',
    # registrations: 'users/registrations',
    # unlocks: 'users/unlocks'
  }
  match '/users/finish_signup' => 'users#finish_signup', via: %i[get patch], as: :finish_signup

  root 'purchases#index'

  get 'purchases/index'
  get 'purchases/history'

  get 'inventory/index'

  get 'permissions/index'

  resources :categories

  namespace :api, defaults: { format: :json } do
    resources :orders,      only: %i[index create show]
    resources :items,       only: %i[index create show update]
    resources :users,       only: %i[index show update] do
      resources :user_abilities,    only: [:create]
      resources :orders,            only: [:index]
    end
    resources :user_abilities, only: [:destroy]
  end

  get 'robots', to: 'robot#show'
  get 'robot', to: 'robot#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>EVE Requisition</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="icon" href="/favicon.ico" type="image/x-icon">
</head>
<body data-controller="<%= params[:controller] %>" data-action="<%= params[:action] %>">

  <!-- Fixed navbar -->
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Requisition</a>
        <% if Rails.env.development? %>
          <div class="navbar-left" style="color:white;">
            <%= render 'shared/debug_responsive' %>
          </div>
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="top-navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to('Orders', purchases_history_path) %></li>
            <% if current_user.can_view_users? %>
              <li><%= link_to('Permissions', permissions_index_path) %></li>
            <% end %>
            <% if current_user.can_view_inventory? %>
              <li><%= link_to('Inventory', inventory_index_path) %></li>
            <% end %>
            <% if current_user.can_view_category? %>
              <li><%= link_to('Categories', categories_path) %></li>
            <% end %>
            <li role="presentation" class="avatar dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <%= image_tag current_user.image_url, class: "img-responsive img-rounded" %>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to('Sign up', eve_sign_up_url, target: '_blank') %></li>
            <li>
              <a href="<%= user_eve_online_omniauth_authorize_path %>" class="eve-login">
                <%= image_tag eve_log_in_image_url, alt: 'eve online log in' %>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <%= render 'shared/alerts' %>

  <div>
    <%= yield %>
  </div>
</body>
</html>